[workspace]
members=[ "js-runtime-lib","swc-cfg", "swc-emit-rust", "swc-opt-ssa", "swc-ssa", "swc-tac"]
resolver="2"

[workspace.dependencies]
anyhow = "1.0.87"
bimap = "0.6.3"
id-arena = "2.2.1"
arena-traits = {version="0.2.0",features=["id-arena"]}
ssa-traits = "0.2.0"
cfg-traits = "0.2.0"
ssa-impls = "0.2.0"
ssa-reloop = "0.2.0"
swc_atoms = "2.0.0"
swc_common = "4.0.0"
swc_ecma_ast = "4.0.0"
swc_ecma_compat_es2015 = "5.0.0"
swc_ecma_minifier = "5.0.0"
swc_ecma_transforms_base = "5.0.0"
swc_ecma_utils = "5.0.0"
swc_ecma_visit = "4.0.0"

proc-macro2 = "1.0.88"
quasiquote = "0.1.1"
quote = "1.0.37"
syn = "2.0.82"

portal-pc-waffle="0.3.2"
