[package]
name = "swc-cfg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
id-arena.workspace = true
relooper = "0.1.0"
swc_atoms.workspace = true
swc_common.workspace = true
swc_ecma_ast.workspace = true
swc_ecma_utils.workspace = true
swc_ecma_visit.workspace = true
