[package]
name = "portal-jsc-js-runtime-lib"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "js_runtime_lib"

[dependencies]
anyhow.workspace = true
boxing = "0.1.2"
dumpster = "1.0.0"
itertools = "0.13.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
