[package]
name = "portal-jsc-waffle"
version = "0.1.0"
edition = "2024"

[features]
lower_trace = []

[dependencies]
portal-jsc-swc-cfg.workspace = true
portal-jsc-swc-ssa.workspace = true
portal-jsc-swc-tac.workspace = true
portal-jsc-swc-util.workspace = true

portal-pc-waffle = { workspace = true, features = ["backend"] }
sha3.workspace = true
ryu-js = "1"
swc_atoms.workspace = true
swc_common.workspace = true
swc_ecma_ast.workspace = true
swc_ecma_codegen.workspace = true
swc_ecma_parser.workspace = true

[dev-dependencies]
portal-jsc-mob-emit = { path = "../mobile/portal-jsc-mob-emit" }
portal-jsc-jvm-emit = { path = "../mobile/portal-jsc-jvm-emit" }
portal-jsc-swift-emit = { path = "../mobile/portal-jsc-swift-emit" }
wasmparser = { version = "0.240", features = ["validate"] }
wasmtime = { version = "47", default-features = false, features = ["cranelift", "gc-null", "runtime"] }
